name: tracking
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
<<<<<<< HEAD
<<<<<<< HEAD
  badges: ^3.1.2
=======
>>>>>>> d74cf61 (initial app contains screens and pages and navbar and side menu)
=======
  badges: ^3.1.2
>>>>>>> 318cc33 (add items page and cart handling)
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 318cc33 (add items page and cart handling)
  path: ^1.8.3
  path_provider: ^2.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.1
  sqlite3_flutter_libs: ^0.5.19+1
<<<<<<< HEAD
=======
>>>>>>> d74cf61 (initial app contains screens and pages and navbar and side menu)
=======
>>>>>>> 318cc33 (add items page and cart handling)
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
